spring:
  datasource:
    url: jdbc:h2:mem:Test_DB
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  application:
    name: PAYMENT-SERVICE
  zipkin:
    base-url: http://localhost:9411/

server:
  port: 9091
logging:
  file: E:/personal-projects/Microservice-Softwares/microservice-elk.log